name: 'Setup Python Environment'
description: 'Sets up Python with UV and installs dependencies'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.13'

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        
    - name: Install UV
      shell: bash
      run: pip install uv
      
    - name: Install Dependencies
      shell: bash
      run: |
        # Create virtual environment
        uv venv .venv
        # Activate the virtual environment
        source .venv/bin/activate
        # Install dependencies
        uv pip install --upgrade pip
        uv pip install -e ".[dev]"
        # List installed packages for debugging
        uv pip list