version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - model-data:/app/data
    environment:
      - LOG_LEVEL=INFO
      - API_TITLE=Bad Words API
      - API_DESCRIPTION=An API for profanity detection
      - API_VERSION=1.0.0
      - MAX_TEXT_LENGTH=500
      - RATE_LIMIT_DEFAULT=10/minute
      - MODEL_NAME=ml6team/distilbert-base-german-cased-toxic-comments
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s

volumes:
  model-data:
