export const bad_words_de = [
    'abschaum',
    'affenschwanz',
    'ah du schwein',
    'alter muschi',
    'alter wichser',
    'am blitz geleckt haben',
    'analritter',
    'arsch',
    'arschficker',
    'arschfotze',
    'arschgeige',
    'arschgesicht',
    'arschkeks',
    'arschkriecher',
    'arschlecker',
    'arschloch',
    'auberfeiger',
    'aufgeilen',
    'backpfeifengesicht',
    'bastard',
    'bimbo',
    'bloede kuh',
    'blutige sau',
    'blödmann',
    'bonze',
    'bratze',
    'bruchbude',
    'bumsen',
    'depp',
    'donnerwetter',
    'drecksack',
    'drecksau',
    'dreckskerl',
    'drecksnest',
    'dummbatz',
    'dumme nuss',
    'dummkopf',
    'dumpfbacke',
    'dödel',
    'erarschen',
    'fahr zur hölle',
    'feigling',
    'fick',
    'fick deine mutter',
    'fick dich',
    'fick dich arschloch',
    'fick dich in knie',
    'ficke',
    'ficken',
    'ficker',
    'fickfehler',
    'filzlaus',
    'flachwichser',
    'flittchen',
    'fotze',
    'fotzenlecker',
    'fratze',
    'gottverdammt',
    'hackfresse',
    'halt deinen mund',
    'halt die fotze',
    'halt die klappe',
    'hat jemand dir ins gehirn geschissen',
    'hirnrissig',
    'homo',
    'hosenscheisser',
    'huhrensohn',
    'hure',
    'huren',
    'huren sohn',
    'hurensohn',
    'ich ficke deine mutter',
    'ich ficke deine schwester',
    'ich hasse dich',
    'ich will dich ficken',
    'ich will ficken',
    'idiot',
    'ische',
    'kackbratze',
    'kacke',
    'kacken',
    'kackwurst',
    'kampflesbe',
    'kanake',
    'kimme',
    'klugscheißer',
    'küss meinen arsch',
    'lech mien arsch',
    'leck mich',
    'leck mich am arsch',
    'lesbe',
    'lick',
    'lms',
    'lusche',
    'lutsch mein schwanz',
    'lutsch meine eier',
    'lutschen',
    'lümmel',
    'milf',
    'mist',
    'mistkerl',
    'miststück',
    'morgenlatte',
    'mufti',
    'muschi',
    'muschi lecker',
    'mutterficker',
    'möpse',
    'möse',
    'nackt',
    'neger',
    'nigger',
    'nippel',
    'nutte',
    'ohne scheiß',
    'onanieren',
    'orgasmus',
    'penis',
    'penner',
    'pimmel',
    'pimpern',
    'pinkeln',
    'pisse',
    'pissen',
    'pisser',
    'popel',
    'poppen',
    'porno',
    'puff',
    'quatsch',
    'reudig',
    'rosette',
    'sau',
    'saugen',
    'schabracke',
    'scheiss',
    'scheissdreck',
    'scheisse',
    'scheissekopf',
    'scheissen',
    'scheisser',
    'scheisskerl',
    'scheisskopf',
    'scheiße',
    'schiesser',
    'schlampe',
    'schnackeln',
    'schnoodle noodle',
    'schwanz',
    'schwanzlutscher',
    'schwein',
    'schweinebacke',
    'schweinehund',
    'schwuchtel',
    'schwuchtl',
    'shaisa',
    'sheisse',
    'sohn einer hündin',
    'spasti',
    'spießig',
    'spinnen',
    'spinner',
    'spinnst',
    'stinkpot',
    'teufel',
    'tittchen',
    'titten',
    'trottel',
    'verarsche',
    'verdammt',
    'verdammte scheiße',
    'verdammter',
    'verdammter scheiß',
    'verfluchter',
    'verpiss dich',
    'verrückter mann',
    'vollidiot',
    'vollpfosten',
    'vollscheißen',
    'volltrottel',
    'vögeln',
    'was zum teufel',
    'was zur hölle',
    'weichei',
    'wichse',
    'wichsen',
    'wichser',
    'witzbold',
    'zicke',
    'zur holle mit dir'
]